twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locale: '%locale%'
        locales: '%app_locales%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'bootstrap_4_horizontal_layout.html.twig'
